dist: trusty
sudo: required
language: node_js
node_js:
  - "8"

services:
  - docker

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli@6.1.1

script:
  - ng build --prod --aot
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/ccsi-upright-frontend .
  - docker images
  - docker push $DOCKER_USERNAME/ccsi-upright-frontend