sudo: required

services:
  - docker

branches:
  only:
    - master

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t $DOCKER_USERNAME/ccsi-upright-frontend .
  - docker images
  - docker push $DOCKER_USERNAME/ccsi-upright-frontend